export const db = {
    
    "error": false,
    "message": "A busca foi realizada com sucesso!",
    "data": [
        {
            "id": 16,
            "codigo_imovel": "516635",
            "codigo_proprietario": "993686",
            "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
            "estado": null,
            "cidade": "Rio de Janeiro",
            "endereco": "Rua Capitão Ricardo Kirk",
            "bairro": "Santa Cruz",
            "codigo_enderecamento_postal": "23570180",
            "tipo_imovel": null,
            "numero_bloco": "2",
            "complemento": "Casa",
            "andar": "0",
            "quartos_incluindo_suites": 4,
            "suites": 4,
            "banheiros": 4,
            "garagens": 2,
            "metros_quadrados": "800",
            "entrada_no_imovel": null,
            "pessoas_no_imovel": 1,
            "animais_estimacao": 0,
            "piscina": 1,
            "horario_portaria": 3,
            "relacao_imovel": 2,
            "exclusividade": null,
            "status_imovel": null,
            "observacoes": null,
            "tipo_chave": 1,
            "valor_condominio": "630",
            "iptu": 2,
            "iptu_ultimo_pagamento": 0,
            "iptu_ultimo_pagamento_a_vista": "0",
            "iptu_ultimo_pagamento_parcelado": 0,
            "iptu_ultimo_pagamento_parcelado_valor_parcela": "0",
            "iptu_adicional": 0,
            "iptu_adicional_ultimo_pagamento": 0,
            "iptu_adicional_ultimo_pagamento_a_vista": "0",
            "iptu_adicional_ultimo_pagamento_parcelado": 0,
            "iptu_adicional_ultimo_pagamento_parcelado_valor_parcela": "0",
            "tempo_de_espera_de_venda": 1,
            "valor_venda": "1990000",
            "created": "2023-12-26T16:05:42.627Z",
            "modifed": null,
            "valor_aluguel": "0",
            "tipo_anuncio": 2,
            "unidade_federativa": "RJ",
            "pais": "Brasil",
            "search_propertie_localization_url_sanitizer": "santa-cruz-rio-de-janeiro-rj-brasil",
            "avaliacao_renda": 1,
            "avaliacao_score_credito": 2,
            "fiador": 1,
            "deposito_causao": 1,
            "outros_tipos_seguros": 1,
            "fotos": [
                {
                    "id": 91,
                    "codigo_imovel": "516635",
                    "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703606739965-w9m9IE1B9OV6aRk7QAw0-KzdsTYa0zHgZ2m60w7u2429915N6u.jpeg",
                    "posicao_foto_anuncio": 0,
                    "created": "2023-12-26T16:05:48.489Z"
                },
                {
                    "id": 92,
                    "codigo_imovel": "516635",
                    "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703606739996-6f63s3BnxQ6P87o937Q39plVgQ0aWVbBlm9S0Q16UQ9Ow6e6wB.jpeg",
                    "posicao_foto_anuncio": 1,
                    "created": "2023-12-26T16:05:49.494Z"
                },
                {
                    "id": 93,
                    "codigo_imovel": "516635",
                    "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703606740006-6Y3hL-I7obZ0wU1qO9UU26fUEP.01Y.fXFb3M90CO61ECqUB1F.jpeg",
                    "posicao_foto_anuncio": 2,
                    "created": "2023-12-26T16:05:50.500Z"
                },
                {
                    "id": 94,
                    "codigo_imovel": "516635",
                    "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703606740016-GzJ70CTDx6.k61Gc1s6I.kO.W5lK09yI40D0I3lfcrWxtI2obx.jpeg",
                    "posicao_foto_anuncio": 3,
                    "created": "2023-12-26T16:05:51.506Z"
                },
                {
                    "id": 95,
                    "codigo_imovel": "516635",
                    "access_token": "VwqaRK8g7EZ64S0oah6kB588EbJF1sxyIkR.g.vda9-hmU16xk",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703606740026-X26S0-RmNJHS0s4JSG1UTK33.TSeU8_0-i4Khdc7mcpg71ib7Y.jpeg",
                    "posicao_foto_anuncio": 4,
                    "created": "2023-12-26T16:05:52.507Z"
                }
            ]
        },
        {
            "id": 15,
            "codigo_imovel": "688527",
            "codigo_proprietario": "993686",
            "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
            "estado": null,
            "cidade": "Brasília",
            "endereco": "QNL 12 Bloco I",
            "bairro": "Taguatinga Norte (Taguatinga)",
            "codigo_enderecamento_postal": "72156219",
            "tipo_imovel": null,
            "numero_bloco": "6",
            "complemento": "Casa",
            "andar": "0",
            "quartos_incluindo_suites": 1500,
            "suites": 3,
            "banheiros": 3,
            "garagens": 1,
            "metros_quadrados": "800",
            "entrada_no_imovel": null,
            "pessoas_no_imovel": 3,
            "animais_estimacao": 0,
            "piscina": 2,
            "horario_portaria": 4,
            "relacao_imovel": 1,
            "exclusividade": null,
            "status_imovel": null,
            "observacoes": null,
            "tipo_chave": 2,
            "valor_condominio": "200",
            "iptu": 2,
            "iptu_ultimo_pagamento": 0,
            "iptu_ultimo_pagamento_a_vista": "0",
            "iptu_ultimo_pagamento_parcelado": 0,
            "iptu_ultimo_pagamento_parcelado_valor_parcela": "0",
            "iptu_adicional": 0,
            "iptu_adicional_ultimo_pagamento": 0,
            "iptu_adicional_ultimo_pagamento_a_vista": "0",
            "iptu_adicional_ultimo_pagamento_parcelado": 0,
            "iptu_adicional_ultimo_pagamento_parcelado_valor_parcela": "0",
            "tempo_de_espera_de_venda": 5,
            "valor_venda": "1600000",
            "created": "2023-12-26T15:49:30.014Z",
            "modifed": null,
            "valor_aluguel": "0",
            "tipo_anuncio": 2,
            "unidade_federativa": "DF",
            "pais": "Brasil",
            "search_propertie_localization_url_sanitizer": "taguatinga-norte-taguatinga-brasilia-df-brasil",
            "avaliacao_renda": 1,
            "avaliacao_score_credito": 2,
            "fiador": 1,
            "deposito_causao": 1,
            "outros_tipos_seguros": 1,
            "fotos": [
                {
                    "id": 86,
                    "codigo_imovel": "688527",
                    "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605767236-rtPQPwv6yk2KCJCHz667-OvdIFqQ6736KWT665foe1POM127aR.jpeg",
                    "posicao_foto_anuncio": 0,
                    "created": "2023-12-26T15:49:36.309Z"
                },
                {
                    "id": 87,
                    "codigo_imovel": "688527",
                    "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605767308-itW7Wu575dGAHro9e2lkGHcHFHL.xv4_NAPigL1f7ZOeW78EmN.jpeg",
                    "posicao_foto_anuncio": 1,
                    "created": "2023-12-26T15:49:37.339Z"
                },
                {
                    "id": 88,
                    "codigo_imovel": "688527",
                    "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605767431-4QW3Vm0RGkOipA3-ckBmbowv.bRcys3Q75l.NJL3mae40lZ01r.jpeg",
                    "posicao_foto_anuncio": 2,
                    "created": "2023-12-26T15:49:38.362Z"
                },
                {
                    "id": 89,
                    "codigo_imovel": "688527",
                    "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605767449-6476X6haVAUfHx4lX2JlB56w--6nSmQCti7lfqc49YF49ft4D6.jpeg",
                    "posicao_foto_anuncio": 3,
                    "created": "2023-12-26T15:49:39.355Z"
                },
                {
                    "id": 90,
                    "codigo_imovel": "688527",
                    "access_token": "Sb-Z7-xZiV5dzWS7xJ0olPw.x5EDba5I8wftw913w5Xf60_ti7",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605767463-0hitKL7T35o63MeHFEny5Q0F3rv.HCa0U7kcZWb03AvA03L351.jpeg",
                    "posicao_foto_anuncio": 4,
                    "created": "2023-12-26T15:49:40.360Z"
                }
            ]
        },
        {
            "id": 14,
            "codigo_imovel": "366362",
            "codigo_proprietario": "993686",
            "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
            "estado": null,
            "cidade": "Brasília",
            "endereco": "SHIN QI 10 Conjunto 7",
            "bairro": "Setor de Habitações Individuais Norte",
            "codigo_enderecamento_postal": "71525070",
            "tipo_imovel": null,
            "numero_bloco": "15",
            "complemento": "Casa",
            "andar": "0",
            "quartos_incluindo_suites": 5,
            "suites": 5,
            "banheiros": 6,
            "garagens": 2,
            "metros_quadrados": "2400",
            "entrada_no_imovel": null,
            "pessoas_no_imovel": 3,
            "animais_estimacao": 0,
            "piscina": 1,
            "horario_portaria": 1,
            "relacao_imovel": 2,
            "exclusividade": null,
            "status_imovel": null,
            "observacoes": null,
            "tipo_chave": 3,
            "valor_condominio": "1300",
            "iptu": 2,
            "iptu_ultimo_pagamento": 0,
            "iptu_ultimo_pagamento_a_vista": "0",
            "iptu_ultimo_pagamento_parcelado": 0,
            "iptu_ultimo_pagamento_parcelado_valor_parcela": "0",
            "iptu_adicional": 0,
            "iptu_adicional_ultimo_pagamento": 0,
            "iptu_adicional_ultimo_pagamento_a_vista": "0",
            "iptu_adicional_ultimo_pagamento_parcelado": 0,
            "iptu_adicional_ultimo_pagamento_parcelado_valor_parcela": "0",
            "tempo_de_espera_de_venda": 4,
            "valor_venda": "1190000",
            "created": "2023-12-26T15:39:08.585Z",
            "modifed": null,
            "valor_aluguel": "0",
            "tipo_anuncio": 2,
            "unidade_federativa": "DF",
            "pais": "Brasil",
            "search_propertie_localization_url_sanitizer": "setor-de-habitacoes-individuais-norte-brasilia-df-brasil",
            "avaliacao_renda": 1,
            "avaliacao_score_credito": 2,
            "fiador": 1,
            "deposito_causao": 1,
            "outros_tipos_seguros": 1,
            "fotos": [
                {
                    "id": 81,
                    "codigo_imovel": "366362",
                    "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605145651-X2LiDJbMQLkVSa02p_p11UHj667hOI65plJiPJnr_aLgo6gQGD.jpeg",
                    "posicao_foto_anuncio": 0,
                    "created": "2023-12-26T15:39:14.991Z"
                },
                {
                    "id": 82,
                    "codigo_imovel": "366362",
                    "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605145720-VM31uLo5mL11n6Ld61fow6iL5o56M79M0U4XC7Dj5inZPRy3n6.jpeg",
                    "posicao_foto_anuncio": 1,
                    "created": "2023-12-26T15:39:16.002Z"
                },
                {
                    "id": 83,
                    "codigo_imovel": "366362",
                    "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605145728-6DcVX497KR4N1Kf6K2R4.051CjpC9j3KXiw7CMPEg14lm3l505.jpeg",
                    "posicao_foto_anuncio": 2,
                    "created": "2023-12-26T15:39:17.016Z"
                },
                {
                    "id": 84,
                    "codigo_imovel": "366362",
                    "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605145744-HeWuAkuv54VLQiMBn98d44oX4nsnp9yF_oy1a5qPzP7zx76h0h.jpeg",
                    "posicao_foto_anuncio": 3,
                    "created": "2023-12-26T15:39:17.996Z"
                },
                {
                    "id": 85,
                    "codigo_imovel": "366362",
                    "access_token": ".YQ4N9fyFkvOS23s1q5Jh3r_bvK.Zee01nrE0g0xsWcsc0HCPL",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703605145758-bd17tRAV3Kb0JXasP7OO72111BtKjXogpQCP0OCEn4cw8d.gl2.jpeg",
                    "posicao_foto_anuncio": 4,
                    "created": "2023-12-26T15:39:18.993Z"
                }
            ]
        },
        {
            "id": 13,
            "codigo_imovel": "298208",
            "codigo_proprietario": "993686",
            "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
            "estado": null,
            "cidade": "Natal",
            "endereco": "Rua Aderbal de Figueiredo",
            "bairro": "Praia do Meio",
            "codigo_enderecamento_postal": "59010115",
            "tipo_imovel": null,
            "numero_bloco": "B",
            "complemento": "Lote",
            "andar": "2",
            "quartos_incluindo_suites": 4,
            "suites": 3,
            "banheiros": 3,
            "garagens": 1,
            "metros_quadrados": "580",
            "entrada_no_imovel": null,
            "pessoas_no_imovel": 3,
            "animais_estimacao": 0,
            "piscina": 1,
            "horario_portaria": 1,
            "relacao_imovel": 2,
            "exclusividade": null,
            "status_imovel": null,
            "observacoes": null,
            "tipo_chave": 1,
            "valor_condominio": "500",
            "iptu": 2,
            "iptu_ultimo_pagamento": 0,
            "iptu_ultimo_pagamento_a_vista": "0",
            "iptu_ultimo_pagamento_parcelado": 0,
            "iptu_ultimo_pagamento_parcelado_valor_parcela": "0",
            "iptu_adicional": 0,
            "iptu_adicional_ultimo_pagamento": 0,
            "iptu_adicional_ultimo_pagamento_a_vista": "0",
            "iptu_adicional_ultimo_pagamento_parcelado": 0,
            "iptu_adicional_ultimo_pagamento_parcelado_valor_parcela": "0",
            "tempo_de_espera_de_venda": 1,
            "valor_venda": "800000",
            "created": "2023-12-22T20:07:11.190Z",
            "modifed": null,
            "valor_aluguel": "0",
            "tipo_anuncio": 2,
            "unidade_federativa": "RN",
            "pais": "Brasil",
            "search_propertie_localization_url_sanitizer": "praia-do-meio-natal-rn-brasil",
            "avaliacao_renda": 1,
            "avaliacao_score_credito": 2,
            "fiador": 1,
            "deposito_causao": 1,
            "outros_tipos_seguros": 1,
            "fotos": [
                {
                    "id": 76,
                    "codigo_imovel": "298208",
                    "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703275625589-1-7_Cfz.7xCyhA58U5t5iDIX564t7Lz6Yw51XnR2tOa4l90P1m.jpeg",
                    "posicao_foto_anuncio": 0,
                    "created": "2023-12-22T20:07:18.885Z"
                },
                {
                    "id": 77,
                    "codigo_imovel": "298208",
                    "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703275626146-enNt4YgUrt.WLXr7t2Y06TOzYWUExL0Bf-JMn3RR07KYe3p6DI.jpeg",
                    "posicao_foto_anuncio": 1,
                    "created": "2023-12-22T20:07:19.907Z"
                },
                {
                    "id": 78,
                    "codigo_imovel": "298208",
                    "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703275626242-dyEG-55rkN612VB7A2qI75hWI27Op2R9TX5mB7.ntOhY444792.jpeg",
                    "posicao_foto_anuncio": 2,
                    "created": "2023-12-22T20:07:20.945Z"
                },
                {
                    "id": 79,
                    "codigo_imovel": "298208",
                    "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703275626380-IY201qscCYb0iLR73R6HFYQDQp030Ihr7Yd9GPe0M2f_VfPWQv.jpeg",
                    "posicao_foto_anuncio": 3,
                    "created": "2023-12-22T20:07:22.000Z"
                },
                {
                    "id": 80,
                    "codigo_imovel": "298208",
                    "access_token": "qmHwH4YyNwMyAzf0JQ.Q-f_Z0-Y9b_lyoOlo49C6FaRFdagWyi",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1703275626394-1WC7ujMt6EsytzvI134hGfZTHswBcN1f_7JphG2.Dhg8h1KIYc.jpeg",
                    "posicao_foto_anuncio": 4,
                    "created": "2023-12-22T20:07:23.041Z"
                }
            ]
        },
        {
            "id": 12,
            "codigo_imovel": "456790",
            "codigo_proprietario": "993686",
            "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
            "estado": null,
            "cidade": "Salvador",
            "endereco": "Rua Eva Adler",
            "bairro": "Caminho das Árvores",
            "codigo_enderecamento_postal": "41820170",
            "tipo_imovel": null,
            "numero_bloco": "3",
            "complemento": "Condomínio",
            "andar": "0",
            "quartos_incluindo_suites": 4,
            "suites": 3,
            "banheiros": 3,
            "garagens": 1,
            "metros_quadrados": "4788",
            "entrada_no_imovel": null,
            "pessoas_no_imovel": 3,
            "animais_estimacao": 1,
            "piscina": 1,
            "horario_portaria": 1,
            "relacao_imovel": 1,
            "exclusividade": null,
            "status_imovel": null,
            "observacoes": null,
            "tipo_chave": 1,
            "valor_condominio": "1050",
            "iptu": 2,
            "iptu_ultimo_pagamento": 0,
            "iptu_ultimo_pagamento_a_vista": "0",
            "iptu_ultimo_pagamento_parcelado": 0,
            "iptu_ultimo_pagamento_parcelado_valor_parcela": "0",
            "iptu_adicional": 0,
            "iptu_adicional_ultimo_pagamento": 0,
            "iptu_adicional_ultimo_pagamento_a_vista": "0",
            "iptu_adicional_ultimo_pagamento_parcelado": 0,
            "iptu_adicional_ultimo_pagamento_parcelado_valor_parcela": "0",
            "tempo_de_espera_de_venda": 1,
            "valor_venda": "390000",
            "created": "2023-12-17T13:25:38.163Z",
            "modifed": null,
            "valor_aluguel": "0",
            "tipo_anuncio": 2,
            "unidade_federativa": "BA",
            "pais": "Brasil",
            "search_propertie_localization_url_sanitizer": "caminho-das-arvores-salvador-ba-brasil",
            "avaliacao_renda": 1,
            "avaliacao_score_credito": 2,
            "fiador": 1,
            "deposito_causao": 1,
            "outros_tipos_seguros": 1,
            "fotos": [
                {
                    "id": 71,
                    "codigo_imovel": "456790",
                    "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1702819533824-F3GoZZuE3-8YZ93Svv7.gUFxTDGy_zXAZB.AmpW2HN4NjELhF9.jpeg",
                    "posicao_foto_anuncio": 0,
                    "created": "2023-12-17T13:25:46.841Z"
                },
                {
                    "id": 72,
                    "codigo_imovel": "456790",
                    "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1702819534104-QI0vqhocz6aW3Pm8n0N_N9IDPLe8h83oFfWYf31alQObSTS2c0.jpeg",
                    "posicao_foto_anuncio": 1,
                    "created": "2023-12-17T13:25:47.862Z"
                },
                {
                    "id": 73,
                    "codigo_imovel": "456790",
                    "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1702819534130-0K18lEUvFIz3190o22Qmu8m1r.i4Inbw3i051KVK_1gRabT8Kx.jpeg",
                    "posicao_foto_anuncio": 2,
                    "created": "2023-12-17T13:25:48.854Z"
                },
                {
                    "id": 74,
                    "codigo_imovel": "456790",
                    "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1702819534342-Q26sot02bob5K1LKmR7Gg6p49aJSHQGvH10NMCyL1-sXL8HaVK.jpeg",
                    "posicao_foto_anuncio": 3,
                    "created": "2023-12-17T13:25:49.830Z"
                },
                {
                    "id": 75,
                    "codigo_imovel": "456790",
                    "access_token": "km4G6YpD6Ejy3BK_bn_J6S1pIWmTyk2ILEChuTZ8O688xXiTIP",
                    "nome_arquivo": "https://storage.googleapis.com/mary-fifi-properties/images-121023%2F1702819534373-auO2-tz4ggNd.u2B60S3A3JB7WL79XX2x9m_OUpnv1aaOGo.q8.jpeg",
                    "posicao_foto_anuncio": 4,
                    "created": "2023-12-17T13:25:50.810Z"
                }
            ]
        }
    ]
}